#ifndef HBRIDGE_CONFIG_H
#define HBRIDGE_CONFIG_H

#define HBRIDGE_TRANSISTOR1_PORT   PORTB
#define HBRIDGE_TRANSISTOR2_PORT   PORTB

#define HBRIDGE_TRANSISTOR1_PIN    PIN0
#define HBRIDGE_TRANSISTOR2_PIN    PIN1

#endif
