#include"../../LIB/STD_TYPES.h"

#include "../../MCAL/DIO/DIO_interface.h"

#include"HBRIDGE_interface.h"
#include"HBRIDGE_private.h"
#include"HBRIDGE_config.h"

void HBRIDGE_voidTrans1HighTrans2Low(void)
{
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR2_PORT,HBRIDGE_TRANSISTOR2_PIN, LOW);
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR1_PORT,HBRIDGE_TRANSISTOR1_PIN, HIGH);
}

void HBRIDGE_voidTrans2HighTrans1Low(void)
{
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR1_PORT,HBRIDGE_TRANSISTOR1_PIN, LOW);
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR2_PORT,HBRIDGE_TRANSISTOR2_PIN, HIGH);
}

void HBRIDGE_voidInit(void)
{
	DIO_voidSetPinDirection(HBRIDGE_TRANSISTOR1_PORT,HBRIDGE_TRANSISTOR1_PIN, OUTPUT);
	DIO_voidSetPinDirection(HBRIDGE_TRANSISTOR2_PORT,HBRIDGE_TRANSISTOR2_PIN, OUTPUT);
}

void HBRIDGE_voidTrans2LowTrans1Low(void)
{
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR1_PORT,HBRIDGE_TRANSISTOR1_PIN, LOW);
	DIO_voidSetPinValue(HBRIDGE_TRANSISTOR2_PORT,HBRIDGE_TRANSISTOR2_PIN, LOW);
}




