#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

#define EXTI_INT0_ENABLE  ENABLE
#define EXTI_INT1_ENABLE  ENABLE
#define EXTI_INT2_ENABLE  ENABLE

/*FALLING_EDGE
 RISING_EDGE
 ON_CHANGE
 LOW_LEVEL      */

#define EXTI_INT0_SENSE_CONTROL  FALLING_EDGE
#define EXTI_INT1_SENSE_CONTROL  FALLING_EDGE
#define EXTI_INT2_SENSE_CONTROL  FALLING_EDGE

#endif
